#!/usr/bin/python

name1 = "praful"
height1 = 2
weight1 = 60

name2 = "falguni"
height2 = 1.8
weight2 = 80

name3 = "prakash"
height3 = 2.5
weight3 = 160


def bmi_calc(name, height, weight):
    bmi = weight / (height ** 2)
    print ("bmi")
    print(bmi)
    if bmi < 25:
        return name + " no overweight"
    else:
        return name + " is overwieight"
        
result1 = bmi_calc(name1, height1, weight1)
result2 = bmi_calc(name2, height2, weight2)
result3 = bmi_calc(name3, height3, weight3)
print(result1)
print(result2)
print(result3)
